version: '3'

services:
  musician:
    image: musician:0.0.1
    restart: always
    depends_on:
      - musician-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://musician-db:5432/postgres

  instrument:
    image: instrument:0.0.1
    restart: always
    depends_on:
      - instrument-db
      - musician
    environment:
      MUSIC_MUSICIAN_URL: "http://musician:8081"
      SPRING_DATASOURCE_URL: jdbc:postgresql://instrument-db:5432/postgres

  gateway:
    image: gateway:0.0.1
    restart: always
    environment:
      MUSIC_MUSICIAN_URL: "http://musician:8081"
      MUSIC_INSTRUMENT_URL: "http://instrument:8082"
      MUSIC_GATEWAY_HOST: "gateway:8080"
    depends_on:
      - musician
      - instrument

  webapp:
    image: webapp:0.0.1
    restart: always
    environment:
      API_URL: http://gateway:8080/api
    ports:
      - "8080:80"
    depends_on:
      - gateway

  musician-db:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=musician_db

  instrument-db:
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=instrument_db
